#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE "USERS_DB";
	CREATE DATABASE "AREA_DB";
	CREATE DATABASE "ATL_DB";
	CREATE DATABASE "AGPT_DB";
	CREATE DATABASE "FF_DB";
	GRANT ALL PRIVILEGES ON DATABASE "USERS_DB" TO "$POSTGRES_USER";
	GRANT ALL PRIVILEGES ON DATABASE "AREA_DB" TO "$POSTGRES_USER";
	GRANT ALL PRIVILEGES ON DATABASE "ATL_DB" TO "$POSTGRES_USER";
	GRANT ALL PRIVILEGES ON DATABASE "AGPT_DB" TO "$POSTGRES_USER";
	GRANT ALL PRIVILEGES ON DATABASE "FF_DB" TO "$POSTGRES_USER";
EOSQL

psql -U $POSTGRES_USER -d USERS_DB -f /dumps/Users.sql
psql -U $POSTGRES_USER -d AREA_DB -f /dumps/Area.sql
psql -U $POSTGRES_USER -d ATL_DB -f /dumps/ActualTotalLoad.sql
psql -U $POSTGRES_USER -d AGPT_DB -f /dumps/AggregatedGenerationPerType.sql
psql -U $POSTGRES_USER -d FF_DB -f /dumps/PhysicalFlow.sql